<%-- 
    Document   : invoice
    Created on : 02-Mar-2023, 8:58:40 pm
    Author     : RITWIK SHAW
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>MedEasy - INVOICE Page</title>
        <!-- Favicons -->
        <link href="images/favicon.png" rel="icon">
        <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
        <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="css/styleInvoice.css">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <body >
        <div class="container">
            <div class="col-md-12">
                <div class="invoice">
                    <!-- begin invoice-company -->
                    <div class="invoice-company text-inverse f-w-600">
                        <span class="pull-right hidden-print">
                            <!--<button type="submit">Mail</button>-->
                            <a href="javascript:;" class="btn btn-sm btn-white m-b-10 p-l-5"><i class="fa fa-file t-plus-1 text-danger fa-fw fa-lg"></i> Export as PDF</a>
                            <!--<a href="javascript:;" onclick="window.print();updateOrder(${Order.getOrderId()},${totalPrice})" class="btn btn-sm btn-white m-b-10 p-l-5"><i class="fa fa-print t-plus-1 fa-fw fa-lg"></i> Print</a>-->
                        </span>
                        MEDEASY PHARMACY<br>
                      <small>9A Lalit Mitra Lane, Kolkata-700004<br></small>
                        <!--+91 934 3231 325-->
                    </div>
                    <!-- end invoice-company -->
                    <!-- begin invoice-header -->
                    <div class="invoice-header">
                        <!--                        <div class="invoice-from">
                                                    <small>from</small>
                                                    <address class="m-t-5 m-b-5">
                                                        <strong class="text-inverse">MedEasy</strong><br>
                                                        9A Lalit Mitra Lane<br>
                                                        Kolkata - 700004<br>
                                                        Phone: +91 900 7366 986<br>
                                                        Fax: +91 900 7366 986
                                                    </address>
                                                </div>-->
                        <div class="invoice-to">
                            <small><i>Customer Details:</i></small>
                            <address class="m-t-5 m-b-5">
                                <strong class="text-inverse">Name: ${Customer.getCustomerName()}</strong><br>
                                <strong>Address: </strong>${Customer.getAddress()}<br>
                                <strong>Phone: </strong> ${Customer.getPhoneNumber()}<br>
                                <strong>EmailId: </strong> ${Customer.getEmailId()}<br>
                                <strong>Prescribed by: </strong> <i>${Order.getDoctorName()}</i>
                            </address>
                        </div>
                        <div class="invoice-date">
                            <small>Generated By:</small>
                            <div class="invoice-detail">
                                <h5>${Employee.getFirstName()} ${Employee.getLastName()}</h5>
                            </div>
                            <small>Invoice No:</small>
                            <div class="invoice-detail">
                                ${Order.getOrderId()}<br>
                            </div>
                            <small>Invoice Date:</small>
                            <div class="date text-inverse m-t-5">${Order.getOrderDateTime()}</div>
                        </div>
                    </div>
                    <!-- end invoice-header -->
                    <!-- begin invoice-content -->
                    <div class="invoice-content">
                        <!-- begin table-responsive -->
                        <div class="table-responsive">
                            <table class="table table-invoice">
                                <thead class="bg-light">
                                    <tr>
                                        <th>PRODUCT NAMES</th>
                                        <th class="text-center" width="20%">RATE</th>
                                        <th class="text-center" width="20%">QUANTITY</th>
                                        <th class="text-right" width="20%">COST</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <c:forEach var="product" items="${ProductList}">
                                        <tr>
                                            <td>
                                                <span class="text-inverse">${product.getProductName()}</span><br>
                                                <small></small>
                                            </td>
                                            <td class="text-center">₹${product.getUnitPrice()}</td>
                                            <td class="text-center">${product.getQuantity()}</td>
                                            <td class="text-right">₹${product.getPrice()}</td>
                                        </tr>
                                    </c:forEach>
                                </tbody>
                            </table>
                        </div>
                        <!-- end table-responsive -->
                        <!-- begin invoice-price -->
                        <div class="invoice-price">
                            <div class="invoice-price-left">
                                <div class="invoice-price-row">
                                    <div class="sub-price" >
                                        <small>SUBTOTAL </small>
                                        ₹<span class="text-inverse">${price}</span>
                                    </div>
                                    <div class="sub-price">
                                        <i class="fa fa-minus text-muted"></i>
                                    </div>
                                    <div class="sub-price" >
                                        <small>DISCOUNT</small>
                                        ₹<span class="text-inverse">
                                            <c:choose>
                                                <c:when test="${price>1000}">
                                                    <c:out value="${price/10}"/>
                                                </c:when>
                                                <c:otherwise>
                                                    <c:out value="0"/>
                                                </c:otherwise>
                                            </c:choose>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="invoice-price-right" >
                                <small>TOTAL</small> ₹<span class="f-w-600" id="finalPrice">
                                    <c:choose>
                                        <c:when test="${price>1000}">
                                            <c:out value="${price - price/10}"/>
                                            <c:set var="totalPrice" value="${price - price/10}"/>
                                        </c:when>
                                        <c:otherwise>
                                            <c:out value="${price}"/>
                                            <c:set var="totalPrice" value="${price}"/>
                                        </c:otherwise>
                                    </c:choose>
                                </span>
                            </div>
                        </div>
                        <!-- end invoice-price -->
                    </div>
                    <!-- end invoice-content -->
                    <!-- begin invoice-note -->
                    <div class="invoice-note">
                        * Make all cheques payable to MedEasy<br>
                        * Payment is due within 30 days<br>
                        * If you have any questions concerning this invoice, contact  MedEasy, 016-18192302, support@medeasy.com
                    </div>
                    <!-- end invoice-note -->
                    <!-- begin invoice-footer -->
                    <div class="invoice-footer">
                        <p class="text-center m-b-5 f-w-600">
                            GET WELL SOON
                        </p>
                        <p class="text-center">
                            <span class="m-r-10"><i class="fa fa-fw fa-lg fa-globe"></i> www.medeasypharmacy.com</span>
                            <span class="m-r-10"><i class="fa fa-fw fa-lg fa-phone"></i> 016-18192302</span>
                            <span class="m-r-10"><i class="fa fa-fw fa-lg fa-envelope"></i> support@MedEasy.com</span>
                        </p>
                    </div>
                    <!-- end invoice-footer -->
                    
            <div class="text-center">
                <a href="javascript:;" onclick="window.print();sendEmail('${Customer.getEmailId()}');completeOrder(${Order.getOrderId()},${totalPrice})" class="btn btn-sm btn-white m-b-10 p-l-5"><i class="fa fa-print t-plus-1 fa-fw fa-lg"></i> Print</a>
            </div>
                </div>
            </div>
        </div>
        <!--    <form action="mailto:ghosalbiswajit11@gmail.com" method="POST" enctype="text/plain">
                    <input type="text" name="Message" value="Thanks For Purchasing from MedEasy GET WELL SOON" hidden>
                    <input type="submit" value="Send"> 
                </form>-->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
                    function completeOrder(orderId, totalPrice) {
                        //alert("hi"+totalPrice);
                        $.ajax({
                            url: 'CompleteOrder',
                            type: 'POST',
                            data: {
                                'totalPrice': totalPrice,
                                'orderId': orderId
                            },
                            success: function () {
                                //alert(responseText);
                                //$("#").html(responseText);
                                window.location = 'homeEmployee.jsp';
                            }
                        });
                    }
                    function sendEmail(emailId) {
                        alert("sendEmail");
                        $.ajax({
                            url: 'SendEmail',
                            type: 'POST',
                            data: {
                                'emailId': emailId
                            },
                            success: function () {
                                alert("sendEmail");
                                location.reload();
                            }
                        });
                    }
        </script>
    </body>
</html>